apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msa-front
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: msa-front=ghcr.io/coinwing/cowing-msa-front
    argocd-image-updater.argoproj.io/msa-front.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
spec:
  project: default
  source:
    repoURL: https://github.com/coinwing/front-service
    targetRevision: prod
    path: chart
  destination:
    server: https://kubernetes.default.svc
    namespace: cowing-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
