name: Semgrep CI for front

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"
  workflow_dispatch: {}
  # schedule:
  #   - cron: '0 0 * * *' #  UTC 시간으로 매일 자정에 실행

permissions:
  contents: read

jobs:
  semgrep:
    name: semgrep-front/ci
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    # Dependabot 제외
    if: (github.actor != 'dependabot[bot]')
    
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep(front)
        run: semgrep --config=p/typescript --config=p/javascript --config=p/security-audit . --fail-on=error
      - name: Upload SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif