name: Semgrep CI for front

on:
  pull_request: {}
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/semgrep.yml"
  workflow_dispatch: {}
  # schedule:
  #   - cron: '0 0 * * *' #  UTC 시간으로 매일 자정에 실행

permissions:
  contents: read

jobs:
  semgrep:
    name: semgrep-front/ci
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    # Dependabot 제외
    if: (github.actor != 'dependabot[bot]')
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Semgrep front(Cloud 기능)
        if: env.SEMGREP_APP_TOKEN != ''
        run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Semgrep front(단순 분석)
        if: env.SEMGREP_APP_TOKEN == ''
        run: semgrep --config=p/typescript .